### ISSUE TITLE
Problems with step "Refactor common build script code"

### ISSUE THREAD

**Issue by takvorian** [gradle-guides/creating-multi-project-builds#11]
I moved the groovy plugin and spock parts to the root project build script and removed them from greeting library and greeter scripts but when I run `gradlew clean build` I get the following error:

```
> Task :greeting-library:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':greeting-library:compileGroovy' property 'groovyClasspath' during up-to-date check.
> Cannot infer Groovy class path because no Groovy Jar was found on class path: [C:\Users\Takvorian\Documents\Entwicklung\java2\org.gradle.guides\creating-multi-project-builds\greeting-library\build\classes\java\main]
```

I double and triple checked all changes but I don't get what the problem is.

**Comment by eitsch** [comment]
Hi @takvorian, i had that too (i guess)

In my case i did not catch the last "to be remaining" line of the file and also deleted that, too. 

After the refactoring the content of the File: greeting-library\build.gradle should look like this (thats what worked for me) (maybe you need to change the version)

```groovy
dependencies {
    compile 'org.codehaus.groovy:groovy:2.4.10'
}
```

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #240](https://github.com/gradle/guides/issues/240) via [**ZenHub**](https://www.zenhub.com/)
