### ISSUE TITLE
CI/CD implication with multi project builds

### ISSUE THREAD

**Issue by jerryyanmj** [gradle-guides/creating-multi-project-builds#26]
I have been practicing this approach in my project for a while.  I think this is a great way to architect multi module project.  However, this does give us some on going challenging with CI/CD setup.  We have the following setup.
- Root project
   + Sub module 1
   + Sub module 2
   + Sub module 3
Each module has its own pipeline and we want each module to be built separately.  However, this setup triggers a webhook call when any module is changed.  With that, I had to give up the current setup and move each module to its own repository.

Let me know your thoughts on my point and I am happy to learn how you get around it.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #294](https://github.com/gradle/guides/issues/294) via [**ZenHub**](https://www.zenhub.com/)
