### ISSUE TITLE
Newbie Problem with Guide Example

### ISSUE THREAD

**Issue by JWT007** [gradle-guides/creating-multi-project-builds#3]
I hope this is the right place to post this.

I am totally new to gradle and was going through the gradle guide (Creating Multi-project Builds).

I ran into a problem which at first confused the heck out of me as someone who has never used Gradle or Groovy before. So I thought I would mention it here in case Schalk wants to add a hint to his guide :smile:

Following the documentation on my Windows machine I set up the GreetingFormatter/Greeter#main (Java) and the GreeterSpec (Groovy). The specification test kept blowing up on me on the simple string test-comparison:

```
class GreeterSpec extends Specification {

    def 'Calling the entry point'() {

        ...

        then: 'The correct greeting is output'
        buf.toString() == "Hello, Gradlephant\n"
    }
}
```
When the test failed and I compared the result with the expected I noticed that a CRLF linefeed was making the difference.

Java was using the System.lineSeparator Property from Windows (CRLF) and Groovy was just using the "\n" (not "\r\n") in the test-string literal which lead to the two strings being unequal. I assume if this guide was followed on a Unix-Variant there would be no problem.

To get it to work I had to make one small change and add a ".denormalize()" to the Groovy String literal.

```
then: 'The correct greeting is output'
buf.toString() == 'Hello, Gradlephant\n'.denormalize()
```
Once I did that the specification test ran through.

On the other forum,  @bmuschko wrote:

> Thanks for reporting. The best place to open these issues is directly in the repository for that guide: https://github.com/gradle-guides/creating-multi-project-builds.
> 
> We usually just test the code of a guide on Linux with Travis CI. That's probably why the issue wasn't caught earlier. The assertion should probably use System.getProperty('line.separator') instead of \n. Alternatively, the assertion could be relaxed by using contains() instead.

**Comment by bmuschko** [comment]
Thanks! Would you be interested in providing a pull request for this? Could you please also sign the CLA in case you are interested?

**Comment by JWT007** [comment]
Sure Benjamin, I would be more than glad to give it a go.

Give me a bit of time though :) will be my first Git/Github experience so I am gonna need to do it slow...

Can you give me tip on how/where to sign the CLA?  I found the github CLA but I could not accept it.

**Comment by eriwen** [comment]
@JWT007 Gradle has changed to use an easier [DCO process](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md#accept-developer-certificate-of-origin) process. So if you submit a change with a proper `--sign-off` via Git, we can accept your change without a CLA.

What do you say?

**Comment by DreamLi1314** [comment]
I also encountered this problem on the Window10 x64 machine and solved it with the method provided by JWT007. The following code shows:
`buf.toString() == "Hello, Gradlephant"+System.getProperty('line.separator').denormalize()`

**Comment by eriwen** [comment]
Fixed with https://github.com/gradle-guides/creating-multi-project-builds/commit/b9df0356b132710aeda15821fe4208fdc2683178
