### ISSUE TITLE
"mainClassName" - build doesn't fail

### ISSUE THREAD

**Issue by figaw** [gradle-guides/creating-multi-project-builds#7]
With the project structure you make in the tutorial, `src/main/greeter/Greeter.java` the build is not failing after adding the `mainClassName = 'greeter.Greeter'` line to the `build.gradle` file.

This is because the java plugin assumes a project layout like `src/main/java/` and therefore, customizing the mainClassName doesn't work.

1. Either change the project structure to `src/main/java/greeter/Greeter.java` and instead add `mainClassName = 'main.java.greeter.Greeter'` to the `build.gradle`-file. This will keep the build-file minimal. Or,

1. keep the project structure, and customize the Java plugin with the sourceSets-directive, by adding to the `build.gradle`-file in the `greeter`-folder, the following,
```
sourceSets {
    main {
        java {
            srcDirs = ['src/main']
        }
    }
} 
```
I'm personally very much in favor of the sourceSets solution, because it teaches people how to specify the location of their code.

**Comment by JWT007** [comment]
I am confused :) I just did this tutorial a few days ago:

In the guide it says:

> Now create a Java class file with a main function, which will consume the Greeter library from the greeting-library subproject.
> 
> $ mkdir -p greeter/src/main/java/greeter
> greeter/src/main/java/greeter/Greeter.java

This is the standard location and worked for me without any problems.

**Comment by figaw** [comment]
My mistake! You're completely right.
